### ISSUE TITLE
[ASSIGN1005] (L[len(L)//2 + 1) does not needed to used repeatly

### ISSUE THREAD

**Issue by SkuldNorniern** [SkuldNorniern/SWP2#2]
https://github.com/SkuldNorniern/SWP2/blob/6b5ec590a2ed5c02a83110c702f263c8415385e8/assignment/assign1005/binarysearch/assign1005_20213000.py#L12-L18

**Comment by toddla23** [comment]
add variablepivot = len(L)//2 + 1
